### ISSUE TITLE
Connecting from one pc on wifi to another pc running lnd

### ISSUE THREAD

**Issue by psqnt** [kornpow/lnd-grpc-client#7]
Hi can I use this library to connect my pc running this lnd-grpc-client to another pc on my network running lnd (mynode) - i've downloaded the admin macaroon and tls cert and used my nodes local pi and 10009 as rpc port however the connection seems to be failing. Any experience with this?

**Comment by kornpow** [comment]
It should work, that is what I am typically doing. I have a node on my home network, and I connect to it from my laptop

Does this help?
https://github.com/kornpow/lnd-grpc-client#create-example-env-file

**Comment by kornpow** [comment]
This should work please re-open if needed
